In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')

In [3]:
from nptweak import to_2darray
import numpy as np

# Convert vector to 2D array

In [4]:
x = np.array([1,2,3])
x = to_2darray(x)
print(x.shape)
x

(3, 1)


array([[1],
       [2],
       [3]])

In [5]:
x = np.array([1,2,3])
x = to_2darray(x, trans=True)
print(x.shape)
x

(1, 3)


array([[1, 2, 3]])

In [6]:
x = np.array([1,2,3])
x = to_2darray(x, flip=True)
print(x.shape)
x

(3, 1)


array([[3],
       [2],
       [1]])

# There is an order
`trans` is executed before `flip`.
And `flip` always means upside-down flip.

The following command would just transpose and flip wouldn't have any effect.

In [7]:
x = np.array([1,2,3])
x = to_2darray(x, trans=True, flip=True)
print(x.shape)
x

(1, 3)


array([[1, 2, 3]])

# 2D array as input 
This is kind of pointless because there is nothing to adjust.

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = to_2darray(x)
print(x.shape)
x

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

Complicated:

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = to_2darray(x, trans=True, flip=False)
print(x.shape)
x

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

Easy:

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = x.T
print(x.shape)
x

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

Complicated:

In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = to_2darray(x, trans=True, flip=True)
print(x.shape)
x

(3, 2)


array([[3, 6],
       [2, 5],
       [1, 4]])

Easy:

In [12]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.flipud(x.T)
print(x.shape)
x

(3, 2)


array([[3, 6],
       [2, 5],
       [1, 4]])